"""add workflow groups and external contacts

Revision ID: 287a79f591c5
Revises: 17e214e17bb6
Create Date: 2026-07-29 14:03:22.051761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287a79f591c5'
down_revision: Union[str, Sequence[str], None] = '17e214e17bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_contacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_contacts_email'), 'external_contacts', ['email'], unique=False)
    op.create_index(op.f('ix_external_contacts_team_id'), 'external_contacts', ['team_id'], unique=False)
    op.create_table('workflow_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_user_id', sa.String(length=36), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manager_user_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_groups_manager_user_id'), 'workflow_groups', ['manager_user_id'], unique=False)
    op.create_index(op.f('ix_workflow_groups_team_id'), 'workflow_groups', ['team_id'], unique=False)
    op.add_column('items', sa.Column('workflow_group_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_items_workflow_group_id'), 'items', ['workflow_group_id'], unique=False)
    op.create_foreign_key(None, 'items', 'workflow_groups', ['workflow_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_index(op.f('ix_items_workflow_group_id'), table_name='items')
    op.drop_column('items', 'workflow_group_id')
    op.drop_index(op.f('ix_workflow_groups_team_id'), table_name='workflow_groups')
    op.drop_index(op.f('ix_workflow_groups_manager_user_id'), table_name='workflow_groups')
    op.drop_table('workflow_groups')
    op.drop_index(op.f('ix_external_contacts_team_id'), table_name='external_contacts')
    op.drop_index(op.f('ix_external_contacts_email'), table_name='external_contacts')
    op.drop_table('external_contacts')
    # ### end Alembic commands ###
