"""add invite name

Revision ID: 354b9275d556
Revises: 9230462ef08b
Create Date: 2026-06-02 11:46:44.737508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354b9275d556'
down_revision: Union[str, Sequence[str], None] = '9230462ef08b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'notifications', 'user_profiles', ['recipient_user_id'], ['id'])
    op.drop_constraint(op.f('team_invites_token_key'), 'team_invites', type_='unique')
    op.drop_index(op.f('ix_team_invites_token'), table_name='team_invites')
    op.create_index(op.f('ix_team_invites_token'), 'team_invites', ['token'], unique=True)
    op.create_index(op.f('ix_team_invites_id'), 'team_invites', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_invites_id'), table_name='team_invites')
    op.drop_index(op.f('ix_team_invites_token'), table_name='team_invites')
    op.create_index(op.f('ix_team_invites_token'), 'team_invites', ['token'], unique=False)
    op.create_unique_constraint(op.f('team_invites_token_key'), 'team_invites', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    # ### end Alembic commands ###
