"""add timezone to reminders

Revision ID: 9230462ef08b
Revises: 39a1f5854596
Create Date: 2026-05-30 01:12:56.384242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9230462ef08b'
down_revision: Union[str, Sequence[str], None] = '39a1f5854596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('timezone', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'timezone')
    # ### end Alembic commands ###
