"""add billing fields to teams

Revision ID: a4d9389d41f5
Revises: 354b9275d556
Create Date: 2026-06-16 11:15:18.214863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d9389d41f5'
down_revision: Union[str, Sequence[str], None] = '354b9275d556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'teams',
        sa.Column(
            'plan',
            sa.String(length=32),
            nullable=False,
            server_default='pending'
        )
    )
    op.add_column('teams', sa.Column('stripe_customer_id', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('stripe_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'stripe_subscription_id')
    op.drop_column('teams', 'stripe_customer_id')
    op.drop_column('teams', 'plan')
    # ### end Alembic commands ###
